### ISSUE TITLE
implement an Events handler

### ISSUE THREAD

**Issue by AnnoyingTechnology** [polyfony-inc/polyfony#104]
## Built in events

* beforeRender
* afterRender
* beforeQuery
* afterQuery
* beforeRouting
* afterRouting
* onException
* onLogin
* onAuthentication

`Private/Bundles/{Name}/Loader/Event.php`

That'd be nice for example  to send `Emails` after a `Response` has been rendered to the user. 
As sending an email usually takes 20 to 250 ms depending on network performance and the location of the SMTP (local, remote). Most of the time, this doubles the generation time of a `Response`. So by actually sending the email after we gave back a `Response` to the user, we'd cut back generation time in half !

in a Controller or in a Email's dedicated helper
```php
(new Emails)->set([
   // bunch of usual stuff here
])->save(); // don't  ->send(), ->save() instead !
```
in a Bundle's `Loader/Config.php` or `Loader/Events.php`
```php
// then leverage this
Polyfony\Events::listenFor(
     'afterRender' // or onShutdown? (dunno...),
     'Models\Emails::sendAllPendings()'
);
```
and of course in the `Emails` model
```php
public static function sendAllPendings() :void {
    foreach(self::_select()->whereEmpty(['sending_date'])->execute() as $email) {
        $email->send();
    }
}
```

More about the [Mediator Pattern](https://en.wikipedia.org/wiki/Mediator_pattern)
Question on StackOverflow [PHP: Event listener best practices ?](
https://stackoverflow.com/questions/4471183/php-event-listener-best-practice-implementation)

```php
// listen to the shutdown event (this one would be 'built-in')
Events::listenFor(
     'onShutdown',
     'Models\Emails::sendAllPending()',
);

// listen to a custom event
Events::listenFor(
     'orderShipping',
     (function() { do_something(); })
);

// and offer to trigger custom events
Events::trigger(
     'orderShipping'
);
````

So it'd be a user-configurable Event dispatcher. 
That *happens* to already have some built-in events triggered from inside the framework. 

@WarenN  Ça t'irait ?

Events implementation in other frameworks : 
* https://github.com/AmineAsli/event_dispatcher
* http://www.inbudapesthotels.com/rubyeventmachinecom/
* https://api.rubyonrails.org/v3.2.13/classes/ActiveRecord/Observer.html
* https://symfony.com/doc/current/event_dispatcher.html
* https://laravel.com/docs/5.8/events

Memo : for the `onShutdown` event.
``` php
register_shutdown_function('shutdownFunction');
        function shutDownFunction() {
            $error = error_get_last();
            if ($error['type'] == 1) { // E_ERROR => http://php.net/manual/fr/errorfunc.constants.php
                // log
                // redirection vers la page d'erreur + notification du dev
            }
        } 
```

**Comment by AnnoyingTechnology** [comment]
Maybe create a class Callback.
```php
// to which one could register an anonymous function to be run at some point
Polyfony\Callbacks::register(
     (function() { echo 'Bye'; }),
     'shutdown'
);

// on an actual function to be run at some point
Polyfony\Callbacks::register(
     'Models\Accounts::cleanup()', 
     'shutdown'
);

// events could be 
const $_events = [
'shutdown'
'query_execute',
'pre_boot',
'post_boot
];

```

**Comment by AnnoyingTechnology** [comment]
Ability to create custom events
```php

// this line in a model or in a controller
Polyfony\Events::trigger('user-account-creation');

```
Would trigger anything previously registered this way

```php

Polyfony\Events::register((function(){}), 'user-account-creation');

```

**Comment by AnnoyingTechnology** [comment]
## Built in events

* before_routing
* after_routing
* before_query (DB)
* after_query (DB)
* after_render
* before_render

d'autres ? @WarenN

**Comment by AnnoyingTechnology** [comment]
That'd be nice to send emails after a page has been rendered to the user. 

```php
// don't sent the email in the controller but just save it
(new Emails)->set(...)->save();

// then leverage this
Polyfony\Events::register(
    'Models\Emails::sendPendings()', 
    'user-account-creation'
);
```


https://github.com/AmineAsli/event_dispatcher
http://www.inbudapesthotels.com/rubyeventmachinecom/
https://api.rubyonrails.org/v3.2.13/classes/ActiveRecord/Observer.html
https://symfony.com/doc/current/event_dispatcher.html
https://laravel.com/docs/5.8/events

**Comment by AnnoyingTechnology** [comment]
Instead of Events::register, let's do 

```php

// listen to the shutdown event
Polyfony\Events::listenFor(
     (function() { echo 'Bye'; }),
     'shutdown'
);

// listen to a custom event
Polyfony\Events::listenFor(
     (function() { do_something(); }),
     'orderShipped'
);

// and offer to trigger custom events
Polyfony\Events::trigger(
     'orderShipped'
);

````

@WarenN  ? vraiment besoin de feedback là dessus. Comme il y a pas mal de façons différentes de faire.

**Comment by AnnoyingTechnology** [comment]
https://stackoverflow.com/questions/4471183/php-event-listener-best-practice-implementation

**Comment by AnnoyingTechnology** [comment]
@WarenN pour le moment je n'ai pas envie d'intégrer des tonnes d'events différents (en suivant le principe : "n'implémenter que ce dont on a vraiment besoin"), je voudrais juste que ça supporte "onTerminate" anciennement afterRender (pour matcher le nomage de symfony), et les évennements personnalisé déclanchés par le développeur.
Ça te va ou tu a besoin d'autres évennement spécifiques ?

**Comment by WarenN** [comment]
@AnnoyingTechnology c'est parfait, et je suis d'accord avec ta remarque

**Comment by AnnoyingTechnology** [comment]
![alrightythen](https://user-images.githubusercontent.com/5336824/60872119-710a2480-a234-11e9-81e1-5e3685197ac6.gif)
