### ISSUE TITLE
Allow SublimeText to suggest methods syntax/use/parameters

### ISSUE THREAD

**Issue by AnnoyingTechnology** [polyfony-inc/polyfony#148]
No idea how to do that. But we need that, so that it can autocomplete `Response::set...` for example

**Comment by Jijac** [comment]
https://docs.sublimetext.info/en/latest/reference/completions.html <https://docs.sublimetext.info/en/latest/reference/completions.html>

**Comment by AnnoyingTechnology** [comment]
trouvé ça https://packagecontrol.io/packages/CompletePHP mais fonctionne pas
AllAutoComplete apporte qq suggestions mais pas top.

**Comment by WarenN** [comment]
J'ai essayé de manipuler les raccourcis d'origine de Sublime Text ...
Basic, mais il n'a rien voulu savoir ... Perte de temps

**Comment by AnnoyingTechnology** [comment]
on va trouver

**Comment by Jijac** [comment]
Quelques pistes possibles :
https://github.com/degouville/sublime-bootstrap4 <https://github.com/degouville/sublime-bootstrap4>


http://www.sublimetext.com/docs/plugin-basics
https://github.com/SublimeText/jQuery <https://github.com/SublimeText/jQuery>
https://github.com/srusskih/SublimeJEDI/blob/master/sublime_jedi/completion.py <https://github.com/srusskih/SublimeJEDI/blob/master/sublime_jedi/completion.py>
https://cnpagency.com/blog/creating-sublime-text-3-plugins-part-1/ <https://cnpagency.com/blog/creating-sublime-text-3-plugins-part-1/>
http://engineering.vinted.com/2016/06/27/how-to-write-sublime-plugin/ <http://engineering.vinted.com/2016/06/27/how-to-write-sublime-plugin/>
https://github.com/erichard/SublimePHPCompanion <https://github.com/erichard/SublimePHPCompanion>
