### ISSUE TITLE
Apache rewrite rules (for documentation)

### ISSUE THREAD

**Issue by Jijac** [polyfony-inc/polyfony#172]
<VirtualHost *:80>
	#ServerName www.example.com

	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/vhosts/polyfony/Public

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
	
	<Directory /var/www/vhosts/polyfony/>
	
		<IfModule mod_rewrite.c>
			RewriteEngine on
			RewriteBase /
			RewriteCond %{REQUEST_FILENAME} !-f
			RewriteCond %{REQUEST_FILENAME} !-d
			RewriteCond %{REQUEST_FILENAME} !-l
			RewriteRule ^.*$ index.php [NC,QSA,L]
		</IfModule>
		
		Require all granted
		
	</Directory>
	
</VirtualHost>

**Comment by AnnoyingTechnology** [comment]
Cool, testé ?

**Comment by AnnoyingTechnology** [comment]
copied to https://github.com/polyfony-inc/polyfony/issues/147

**Comment by Jijac** [comment]
Fonctionne aussi avec .htaccess
RewriteEngine on
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-l
RewriteRule ^.*$ index.php [NC,QSA,L]

Vhost definition
<VirtualHost *:80>
	#ServerName www.example.com

	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/vhosts/apache-sqlite/Public

	#LogLevel info ssl:warn

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	<Directory /var/www/vhosts/apache-sqlite/>
		AllowOverride all
		Require all granted
	</Directory>

</VirtualHost>

**Comment by AnnoyingTechnology** [comment]
Ok, merci je vais l'ajouter alors.
