### ISSUE TITLE
Missing Models/logs

### ISSUE THREAD

**Issue by Jijac** [polyfony-inc/polyfony#179]
Fatal error:  Class '\Models\Logs' not found in /server/www/vhosts/_dev/polyfony/Private/Polyfony/Query.php on line 568

**Comment by AnnoyingTechnology** [comment]
Et ? Il n'est pas supposé exister de class log dans models.

**Comment by Jijac** [comment]
Alors pourquoi cette erreur est générée dans Polyfony/Query.php ?

**Comment by AnnoyingTechnology** [comment]
j'imagine que tu as changé le moteur de log de plaintext à database, sans créer le model associé

**Comment by AnnoyingTechnology** [comment]
my bad, le Prod.ini est en "database". il devrait être laissé par défaut en "file" 
https://github.com/polyfony-inc/polyfony/blob/master/Private/Storage/Defaults/Config/Config.ini#L44

**Comment by Jijac** [comment]
Non j’ai juste installé le framework avec composer create-project --stability=dev polyfony-inc/polyfony your-project-folder
