### ISSUE TITLE
Record->setSafely() should check previously allowed form fields

### ISSUE THREAD

**Issue by AnnoyingTechnology** [polyfony-inc/polyfony#194]
**Abstract**

Every time `Record->input($col)`, `Record->select($col)`, `Record->textarea($col)`, `Record->checkbox($col)` is invoked, 
A method `Record/Form->registerSafeColumn($col)` is invoked, it updates a session variable named `pfFormSafeColumns` which contains an array of the following structure 
```php
<?php
['TheURLOfTheGeneratedForm'=>[
        'table_name'=>'TableA',
	'columns'=>[
		'column_name_1',
		'column_name_2',
		'column_name_3',
		'column_name_4',
		'column_name_n',
	]
]];
?>
```
Hence keeping a list of columns allowed to be edited for the form that was shown to the user during the previous Request.
In the controller, the developer would then be able to `Record->setSafely(Request::post('Table'))` which would remove any column that wasn't authorized before applying the actual `Record->set()`.

Of course, when `Record->setSafely()` is called, its associated columns in `pfFormSafeColumns` gets purged.

The key security points here are 
* `pfFormSafeColumns ` must be purged by `->setSafely`
* Failure to start a session must throw an exception to avoid creating a false sense of security
* A missing array of editable columns must have the same effect as an empty array of editable columns

Caveat(s) 
* Cannot show two different forms, for the same class, on the same page and expect this to be usable

**This would allow the developer to trust that all columns posted for update can actually be updated (but not their actual contents of course, for that there is Record/Filters and Record/Validator).**

Cc @WarenN

**Comment by AnnoyingTechnology** [comment]
To circumvent the caveat, it's simple, associated the List of editable columns, to the URL used to generate the form. This would prevents bugs and allow multiple form to be open simultaneously by the same users, and all would work properly.
Then, if the current URL is the same, or if the referrer is the same, it's all good !

**Comment by WarenN** [comment]
c'est génial !

Quand je te parlais des posts gérés par Process dans un même Model, cela me permettrai d'apporter une cohérence et simplifier mon code (pour ajout et suppression de données et fichiers).

Quand nous en avons discuté, c'est même à une solution similaire que j'avais pensé.

**Comment by AnnoyingTechnology** [comment]
probably rendered moot by https://github.com/polyfony-inc/polyfony/issues/258

**Comment by AnnoyingTechnology** [comment]
clearly rendered moot by #258
