### ISSUE TITLE
Store\TrustedCookie

### ISSUE THREAD

**Issue by AnnoyingTechnology** [polyfony-inc/polyfony#21]
Use `Store\Cookie` but add a hash with private salt to ensure it has not been tampered with

**Comment by AnnoyingTechnology** [comment]
Extends Polyfony\Store\Cookie, as such 
`Private/Polyfony/Store/Cookie/Trusted.php` 
`class Trusted extends Store\Cookie`

**Comment by AnnoyingTechnology** [comment]
@WarenN tu veux le faire? C'était une idée à toi, non ? Je me souviens plus.

**Comment by WarenN** [comment]
oui en effet, ça se croise, je note à faire avec Issue #65

**Comment by AnnoyingTechnology** [comment]
wontfix, storing data in cookie slows down http requests and better alternatives are available
