### ISSUE TITLE
Unit testing Bundle

### ISSUE THREAD

**Issue by AnnoyingTechnology** [polyfony-inc/polyfony#33]
https://phpunit.de/getting-started.html

**Comment by AnnoyingTechnology** [comment]
Or maybe in the `/tools/test/`

**Comment by Jijac** [comment]
généralement c'est dans un dossier à part cf Symfony

Jean-Jacques

**Comment by AnnoyingTechnology** [comment]
also covers https://github.com/SIB-FRANCE/Polyfony2/issues/37

**Comment by AnnoyingTechnology** [comment]
`Private/Tests/`

**Comment by AnnoyingTechnology** [comment]
**Progress is made !** 
We now support composer's autoloader, and so, unit testing libraries.

**Comment by AnnoyingTechnology** [comment]
Moved to https://github.com/polyfony-inc/console/issues/11
