### ISSUE TITLE
Offer an option to disable Browser + IP signature verifications

### ISSUE THREAD

**Issue by AnnoyingTechnology** [polyfony-inc/polyfony#65]
~~Provide a `SoftSecurity` class based on trusted cookies that will not require a database query at each page view to check for the session validity.~~

Offer an option in `Config.ini`
```ini
[security] 
enable_signature_verifications = 1 // or 0
```

**Comment by AnnoyingTechnology** [comment]
@WarenN ça devrait te plaire

**Comment by WarenN** [comment]
Oui j�ai vu passer cette nouvelle fonctionnalit� {
	Et oui �a me plais beaucoup ^^
}

**Comment by AnnoyingTechnology** [comment]
@WarenN tu peux la développer si tu veux en la déclarant dans
`Private/Polyfony/Security/Soft.php` 

```php
class Soft extends Polyfony\Security {}
```

**Comment by WarenN** [comment]
Avec plaisir, dès que possible ^^

**Comment by AnnoyingTechnology** [comment]
fixed in #e0b58de
